-- RetailPOS mobile dashboard login support
-- Run this in a NEW query tab in Supabase.
-- This adds login/profile/store-assignment tables for the web app.
-- It does NOT delete your current data.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  default_store_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_stores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id text not null references public.stores(store_id) on delete cascade,
  role text default 'viewer',
  created_at timestamptz default now(),
  unique (user_id, store_id)
);

create or replace function public.handle_new_dashboard_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_dashboard on auth.users;
create trigger on_auth_user_created_dashboard
  after insert on auth.users
  for each row execute procedure public.handle_new_dashboard_user();

alter table public.profiles enable row level security;
alter table public.user_stores enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "user_stores_select_own" on public.user_stores;
create policy "user_stores_select_own"
on public.user_stores
for select
to authenticated
using (auth.uid() = user_id);

grant usage on schema public to authenticated;
grant select, update on public.profiles to authenticated;
grant select on public.user_stores to authenticated;

-- Optional helper examples:
-- 1) Create users in Authentication -> Users.
-- 2) Assign them to stores with SQL like:
--    insert into public.user_stores (user_id, store_id, role)
--    values ('USER_UUID_HERE', 'store_2', 'owner');
--
-- 3) Optional default store:
--    update public.profiles
--    set default_store_id = 'store_2'
--    where id = 'USER_UUID_HERE';
